language: cpp
os: linux
dist: bionic
sudo: required
services: docker

branches:
    only:
        - master
        - devel
          # TODO: REMOVE WRITING-YML BRANCH
        - writing-yml

before_script:
    - sudo apt update && cat packages.txt | xargs sudo apt install --assume-yes
script:
    - make test

