language: cpp
os: linux
sudo: required
services: docker

branches:
    only:
        - master
        - devel

before_script:
    - sudo apt update && sudo apt install socat
script:
    - make install
    - make test

